"""empty message

Revision ID: 0d9b09cb704b
Revises: None
Create Date: 2021-04-08 12:13:22.974992

"""

# revision identifiers, used by Alembic.
revision = '0d9b09cb704b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
